<?php

namespace app\validation;

use app\model\article;

/**
 * 用户保存文章草稿信息
 * Class UserSaveArticle
 * @package app\validation
 */
class UserSaveArticle extends \pms\Validation
{

    protected function initialize()
    {

        $this->add_where('id', [
            'wheres' => [
                'id' => 'id',
                'user_id' => 'user_id'
            ],
            'model' => article::class,
            'message' => 'exits'
        ]);

        return parent::initialize(); // TODO: Change the autogenerated stub
    }
}